# API Keys Configuration
# Google Gemini API key for image generation and text processing
gemini_api_key: 

# OpenAI API key for DALL-E image generation
openai_api_key: 

# Recraft API key for background removal
recraft_api_key: 


